apps/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreditosView,HomeView,formularioView,ListarAccesorios,RegistroView,LoginView
app_name='app1'
urlpatterns = [
    path('creditos/', CreditosView.as_view(), name='creditos'),
    path('home/', HomeView.as_view(), name='home'),
    path('formulario/', formularioView.as_view(), name='formulario'),
    path('listado/', ListarAccesorios.as_view(), name='listado'),
    path('registro/', RegistroView.as_view(), name='registro'),
    path('login/', LoginView.as_view(), name='login'),
    
]

examenfinal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('apps.home.urls'))

]

apps/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class producto(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    imagen = models.CharField(max_length=1000)
    creacion = models.DateField(auto_now_add=True)
    actualizacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s' % (self.nombre)

class Usuario(models.Model):
    perfil = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.perfil.username

@receiver(post_save, sender=User)
def crear_usuario(sender, instance, created, **kwargs):
    if created:
        Usuario.objects.create(perfil=instance)

@receiver(post_save, sender=User)
def guardar_usuario(sender, instance, created, **kwargs):
    instance.usuario.save()

apps/home/forms.py
from django import forms 
from .models import producto
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class productoForm(forms.ModelForm):
    class Meta:
        model=producto
        fields='__all__'

class RegistroForm(UserCreationForm):
    first_name = forms.CharField(max_length=140,required=True)
    last_name = forms.CharField(max_length=140,required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView
from .forms import productoForm,RegistroForm
from .models import Usuario, producto
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
# Create your views here.

class CreditosView(TemplateView):
    template_name='creditos.html'

class HomeView(TemplateView):
    template_name='index.html'

class formularioView(CreateView):
    template_name= 'formulario.html'
    form_class = productoForm
    success_url = reverse_lazy('app1:listado')

class ListarAccesorios(ListView):
    template_name = 'listado.html'
    model = producto

    def get_queryset(self):
        return producto.objects.all()

class RegistroView(CreateView):
    model = Usuario
    form_class = RegistroForm
    success_url = reverse_lazy('app1:login')

class LoginView(LoginView):
    template_name = 'login.html'

apps/home/templates/base.html
{% load static%}
<!DOCTYPE html>
<!--
 * A Design by GraphBerry
 * Author: GraphBerry
 * Author URL: http://graphberry.com
 * License: http://graphberry.com/pages/license
-->
<html lang="en">
    
    <head>
        <meta charset=utf-8>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {%block titulo %} <title>Inicio</title> {% endblock %}
        <!-- Load Roboto font -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Load css styles -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/pluton.css' %}" />
        <!--[if IE 7]>
            <link rel="stylesheet" type="text/css" href="css/pluton-ie7.css" />
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.cslider.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" />
        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/apple-touch-icon-72.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57.png' %}">
        <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    </head>
    
    <body>
        {% block barra%}
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a href="{% url 'app1:home' %}">
                        <img src="https://umg.edu.gt/miumg/sesion_files/logo_white.png" width="200" height="300" alt="Logo" />
                        <!-- This is website logo -->
                    </a>
                    <!-- Navigation button, visible on small resolution -->
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <i class="icon-menu"></i>
                    </button>
                    <!-- Main navigation -->
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav" id="top-navigation">
                            <li><a href="{% url 'app1:home' %}">Home</a></li>
                            <!-- <li><a href="{% url 'app1:formulario' %}">Formulario</a></li>-->
                            <li><a href="{% url 'app1:listado' %}">Articulos</a></li>
                            <li><a href="{% url 'app1:formulario' %}">Registrar Articulos</a></li> 
                            <li><a href="{% url 'app1:creditos' %}">Creditos</a></li>
                            <li><a href="#"><img src="{% static 'images/carrito.png' %}" width="40" height="20"/>Carrito</a></td></li>
                            <li><a href="{% url 'app1:login' %}">Log Out</a></li>
                        </ul>
                    </div>
                    <!-- End main navigation -->
                </div>
            </div>
        </div>
        {%endblock%}
        <!-- Service section start -->
        <div class="section primary-section" id="service">
            {% block inicio %}
            <div class="container">
                <!-- Start title section -->
                <div class="title">
                    <h1>Bienvenido</h1>
                    <!-- Section's title goes here -->
                    <p>Información de la Empresa</p>
                    <p>Proyecto</p>
                    <!--Simple description for section goes here. -->
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <a href="{% url 'app1:listado' %}"><img class="img-circle" src="{% static 'images/Service1.png' %}" alt="service 1"></a>
                            </div>
                            <h3>Articulos</h3>
                            <p>click aqui para ver nuestros articulos</p>
                            
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="{% static 'images/Service2.png' %}" alt="service 2" />
                            </div>
                            <h3>Clientes</h3>
                            <p>Nosotros estamos comprometidos con nuestra clientela</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="{% static 'images/Service3.png' %}" alt="service 3">
                            </div>
                            <h3>Pedidos</h3>
                            <p>Puede ver sus pedidos aquí</p>
                        </div>
                    </div>
                </div>
            </div>
            {%endblock%}
        </div>
        <!-- Service section end -->
        {% block creditos %}
        <!-- Portfolio section start -->
        
        <!-- Portfolio section end -->
        {%endblock%}
        
        <div class="section secondary-section">
            <div class="triangle"></div>
            <div class="container centered">
                <p class="large-text">La elegancia no es la abundancia de la simplicidad. Es la ausencia de lo complejo</p>
            </div>
        </div>
        {% block contacto%}
        
         {% endblock %}
                <div class="container">
                    <div class="span9 center contact-info">
                        <p class="info-mail">San Pedro Sacatepequez, San Marcos.</p>
                        <p class="info-mail">nzacariasf@miumg.edu.gt</p>
                        <p class="info-mail">+502 46673323</p>
                       
                        <div class="title">
                            <h3>Soy Leyenda</h3>
                        </div>
                    </div>
                    <div class="row-fluid centered">
                        <ul class="social">
                            <li>
                                <a href="https://www.facebook.com/neryjz/" target="_blank">
                                    <span class="icon-facebook-circled"></span>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/GtzfNery" target="_blank">
                                    <span class="icon-twitter-circled"></span>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <span class="icon-gplus-circled"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact section edn -->
        <!-- Footer section start -->
        <div class="footer">
            <p>&copy; 2022 Proyecto Aseguramiento de la calidad del software <a href="https://umg.edu.gt/miumg/" target="_blank">Universidad Mariano Gálvez</a>
        </div>
        <!-- Footer section end -->
        <!-- ScrollUp button start -->
        <div class="scrollup">
            <a href="#">
                <i class="icon-up-open"></i>
            </a>
        </div>
        <!-- ScrollUp button end -->
        <!-- Include javascript -->
        <script src="js/jquery.js"></script>
        <script type="text/javascript" src="{% static 'js/jquery.mixitup.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/modernizr.custom.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.bxslider.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.cslider.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.placeholder.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.inview.js'%}"></script>
        <!-- Load google maps api and call initializeMap function defined in app.js -->
        <script async="" defer="" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initializeMap"></script>
        <!-- css3-mediaqueries.js for IE8 or older -->
        <!--[if lt IE 9]>
            <script src="js/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="{% static 'js/app.js'%}"></script>
    </body>
</html>

apps/home/templates/creditos.html
{% extends 'base.html' %}
{% load static%}
{%block titulo %}           
<title>Creditos</title>
{% endblock %}

{% block creditos %}
<div class="section secondary-section " id="portfolio">
    <div class="triangle"></div>
    <div class="container">
        <div class=" title">
            <h1>Conoce al creador de esta págisna</h1>
            <p>Todo lo puedo en cristo que me fortalece!</p>
        </div>
        <!-- Start details for portfolio project 1 -->
        <div id="single-project">
            <div id="slidingDiv" class="toggleDiv row-fluid single-project">
                <div class="span6">
                    <img src="{% static 'images/yo1.jpg' %}" alt="project 1" />
                </div>
                <div class="span6">
                    <div class="project-description">
                        <div class="project-title clearfix">
                            <h3>Creador del Proyecto</h3>
                            <span class="show_hide close">
                                <i class="icon-cancel"></i>
                            </span>
                        </div>
                        <div class="project-info">
                            <div>
                                <span>Nombre</span>Nery Juan Luis Zacarias Fuentes</div>
                            <div>
                                <span>Fecha</span>24/09/2021</div>
                            <div>
                                <span>Skills</span>HTML5, CSS3, JavaScript</div>
                        </div>
                        <p>Cree en tí! ten fé en tus habilidades! hay que ser humildes y responsables!</p>
                            <span>Télefono</span> +502 46673323
                    </div>
                </div>
            </div>
            
            <p >Algunas de mis paginas creadas:</p>
            <!-- End details for portfolio project 1 -->
            <!-- Start details for portfolio project 2 -->
            <div id="slidingDiv1" class="toggleDiv row-fluid single-project">
                <div class="span6">
                    <img src="https://i.ytimg.com/vi/hLK9bAoTvKQ/maxresdefault.jpg" alt="project 2">
                </div>
                <div class="span6">
                    <div class="project-description">
                        <div class="project-title clearfix">
                            <h3>Facebook</h3>
                            <span class="show_hide close">
                                <i class="icon-cancel"></i>
                            </span>
                        </div>
                        <div class="project-info">
                            <div>
                                <span>Cliente</span>Mark Sukerverg</div>
                            <div>
                                <span>Date</span>July 2013</div>
                            <div>
                                <span>Skills</span>HTML5, CSS3, JavaScript</div>
                            <div>
                                <span>Link</span>http://facebook.com</div>
                        </div>
                        <p>Una pagina simple para personas extraordinarias!</p>
                    </div>
                </div>
            </div>
            <!-- End details for portfolio project 2 -->
            <!-- Start details for portfolio project 3 -->
            <div id="slidingDiv2" class="toggleDiv row-fluid single-project">
                <div class="span6">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-1V7sphI5VSN57Di34t5eMECclHIA0_KMvSRavXIWaXNCFeyTJQFziYF35Z6huS3PczA&usqp=CAU" alt="project 3">
                </div>
                <div class="span6">
                    <div class="project-description">
                        <div class="project-title clearfix">
                            <h3>Twitter</h3>
                            <span class="show_hide close">
                                <i class="icon-cancel"></i>
                            </span>
                        </div>
                        <div class="project-info">
                            <div>
                                <span>Cliente</span>Twitter corporation</div>
                            <div>
                                <span>Date</span>July 2011</div>
                            <div>
                                <span>Skills</span>HTML5, CSS3, JavaScript</div>
                            <div>
                                <span>Link</span>http://twitter.com</div>
                        </div>
                        <p>Me parece que somos una copia de facebook pero para chavos</p>
                    </div>
                </div>
            </div>
            <!-- End details for portfolio project 3 -->
            <!-- Start details for portfolio project 4 -->
            <div id="slidingDiv3" class="toggleDiv row-fluid single-project">
                <div class="span6">
                    <img src="https://www.elimparcial.es/fotos/1/youtube-tv.jpg" alt="project 4">
                </div>
                <div class="span6">
                    <div class="project-description">
                        <div class="project-title clearfix">
                            <h3>Youtube</h3>
                            <span class="show_hide close">
                                <i class="icon-cancel"></i>
                            </span>
                        </div>
                        <div class="project-info">
                            <div>
                                <span>Cliente</span>Google</div>
                            <div>
                                <span>Date</span>Enero 2005</div>
                            <div>
                                <span>Skills</span>HTML5, CSS3, JavaScript</div>
                            <div>
                                <span>Link</span>http://Youtube.com</div>
                        </div>
                        <p>Horas de diversion viendo a otros divertirse</p>
                    </div>
                </div>
            </div>
            <!-- End details for portfolio project 4 -->
            <ul id="portfolio-grid" class="thumbnails row">
                <li class="span4 mix web">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio01.png' %}" alt="project 1">
                        <a href="#single-project" class="more show_hide" rel="#slidingDiv">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix photo">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio02.png'%}" alt="project 2">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv1">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix identity">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio03.png' %}" alt="project 3">
                        <a href="#single-project" class="more show_hide" rel="#slidingDiv2">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix web">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio04.png'%}" alt="project 4">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv3">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix photo">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio05.png'%}" alt="project 5">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv4">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix identity">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio06.png'%}" alt="project 6">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv5">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix web">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio07.png'%}" alt="project 7" />
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv6">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix photo">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio08.png' %}" alt="project 8">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv7">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
                <li class="span4 mix identity">
                    <div class="thumbnail">
                        <img src="{% static 'images/Portfolio09.png'%}" alt="project 9">
                        <a href="#single-project" class="show_hide more" rel="#slidingDiv8">
                            <i class="icon-plus"></i>
                        </a>
                        <h3>Thumbnail label</h3>
                        <p>Thumbnail caption...</p>
                        <div class="mask"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

apps/home/templates/formulario.html
{% extends 'base.html' %}
{% load static%}
{%block titulo %}           
<title>Formulario</title>
{% endblock %}


{% block inicio%}
<h1>Ingreso de Productos</h1>
<style>
    .div-3 {
    background-color: #FBD603;
}
</style>
<form method="POST">
    {% csrf_token %} 


    {% if error %}
    <h2>{{error}}</h2>
    {% else %}

    <form action="#" method="POST" enctype="multipart/form-data">

    <div>
        <div >Nombre</div>
        <div>{{form.nombre}}</div>


    </div>
    <div>
        <div >Tipo</div>
        <div>{{form.tipo}}</div>


    </div>
    <div>
        <div >Imagen</div>
        <div>{{form.imagen}}</div>


    </div>


    <button type = "submit" name="Enviar">Enviar</button>
    </form>
    {% endif %}

</form>
{%endblock%}

apps/home/templates/home/usuario_form.html
{% extends 'base.html' %}
{%block titulo %}           
<title>Registro Usuarios</title>
{% endblock %}

{% block barra%}
<div class="navbar">
    <div class="navbar-inner">
<div class="container">
    <center>
<p>Ingresa tus datos para registrarte</p>
</center>
</div>
</div>
</div>
{% endblock %}


{% block inicio %}
<style>
    .div-1 {
        background-color: #EBEBEB;
    }
    
    .div-2 {
    	background-color: #ABBAEA;
    }
    
    .div-3 {
    	background-color: #FBD603;
    }
</style>
<center>
<div  id="service">
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="Guardar">

</form>
</div>
</center>
{%endblock%}

apps/home/templates/index.html
{% extends 'base.html' %}
{%block titulo %}           
<title>Home</title>
{% endblock %}

apps/home/templates/listado.html
{% extends 'base.html' %}
{% load static%}
{%block titulo %}           
<title>Articulos</title>
{% endblock %}


{% block inicio %}
   

    <div  >
        <h1>Listado de Artículos</h1>
    <table border="3" class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <td class="table-info">Nombre</td>
            <td class="table-info">Tipo</td>
            <td class="table-info">Imagen de referencia</td>
            <td class="table-info">Agregar al carrito</td>
        </tr>
    </thead>
    {% for est in object_list %}
    <tr>
    <td class="table-info" >{{est.nombre}} </td>
    <td class="table-info">{{est.tipo}}</td>
    <td class="table-info"><img src="{{est.imagen}}" width="120" height="40"> </td>
    <td class="table-info"><a href="#"><img src="{% static 'images/carrito.png' %}" width="60" height="40"/></a></td>
    </tr>
{% endfor %}
</table>
</div>
{%endblock%}

apps/home/templates/login.html
{% extends 'base.html' %}
{%block titulo %}           
<title>Login</title>
{% endblock %}
{% block barra%}
<div class="navbar">
    <div class="navbar-inner">
<div class="container">
    <center>
<p>Ingresa o registrate para continuar</p>
</center>
</div>
</div>
</div>
{% endblock %}
{% block inicio %}
<style>
    .div-1 {
        background-color: #EBEBEB;
    }
    
    .div-2 {
    	background-color: #ABBAEA;
    }
    
    .div-3 {
    	background-color: #FBD603;
    }
</style>
<center>
<div  id="service">
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="Guardar">
    <li style="color:#ff0000"><a style="color:#2193f0" href="{% url 'app1:registro' %}">Registrarse</a></li>
</form>
</div>
</center>
{%endblock%}